// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoNa6rxFR7WQBOJE1m2LAOM51nceJJWyg',
    appId: '1:526778655587:web:ed408afeacc357e6536956',
    messagingSenderId: '526778655587',
    projectId: 'sitanamalvian',
    authDomain: 'sitanamalvian.firebaseapp.com',
    storageBucket: 'sitanamalvian.firebasestorage.app',
    measurementId: 'G-B6NECP61PP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSqrwCEWKE7wcNQ7Jc7Hi5Zi41OBv7KEY',
    appId: '1:526778655587:android:d15fe6912b18a9c6536956',
    messagingSenderId: '526778655587',
    projectId: 'sitanamalvian',
    storageBucket: 'sitanamalvian.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2vmLRMvNCBNTNKKiXybkm6J3EFEKS_gU',
    appId: '1:526778655587:ios:57d6783a559df39a536956',
    messagingSenderId: '526778655587',
    projectId: 'sitanamalvian',
    storageBucket: 'sitanamalvian.firebasestorage.app',
    iosBundleId: 'com.example.sitanamAlvianApk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2vmLRMvNCBNTNKKiXybkm6J3EFEKS_gU',
    appId: '1:526778655587:ios:57d6783a559df39a536956',
    messagingSenderId: '526778655587',
    projectId: 'sitanamalvian',
    storageBucket: 'sitanamalvian.firebasestorage.app',
    iosBundleId: 'com.example.sitanamAlvianApk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoNa6rxFR7WQBOJE1m2LAOM51nceJJWyg',
    appId: '1:526778655587:web:1475333f5baec9e4536956',
    messagingSenderId: '526778655587',
    projectId: 'sitanamalvian',
    authDomain: 'sitanamalvian.firebaseapp.com',
    storageBucket: 'sitanamalvian.firebasestorage.app',
    measurementId: 'G-8L498WZFNK',
  );
}
